### ISSUE TITLE
sequential number becomes discrete

### ISSUE THREAD

**Issue by nopnop2002** [festlv/mavbridge#4]
I checked a sequential number of received MAVLINK - MESSAGE.
A sequential number becomes discrete.

Receive Seq# D
Receive Seq# F
Receive Seq# E
.
Receive Seq# 20
Receive Seq# 22
Receive Seq# 21

I expect that the following cord is the cause.

    memcpy(transmit_buf + transmit_buf_size, msg.buf, msg.buf_len); 
    transmit_buf_size += msg.buf_len;
    transmit_buf_packets++;

    if (msg.msgid == 0)
        broadcast_packet(msg);

sending que(Seq#C) ----> Receive C
sending que(Seq#D) ----> Receive D
queing Seq#E
queing Seq#F
sending Seq#F(msg.msgid=0) ----> Receive F
sending que(Seq#E) ----> Receive E
sending que(Seq#F)

Thank you for useful package.

**Comment by festlv** [comment]
Indeed, since I don't generally touch the sequence numbers, the receiver could receive both the packet that is broadcast in the network and packet with identical data which is addressed directly to the receiver.

I don't think it can be easily solved, unless one doesn't need the broadcast functionality. Re-writing the sequence numbers would be a worse idea, because that packet essentially is a duplicate data.

IMO, this should not pose a problem for the following reasons:
1) This is a guaranteed to be a heartbeat packet (msgid=0), so the side effects should be minimal (increased received heartbeat frequency?)
2) Receiver implementation can (should?) discard the packets with identical sequence number.

**Comment by nopnop2002** [comment]
Thank you for replay.
I respect your opinion.

Please close this issue.
